[package]
package = "com.example.myapp"
version = "1.0.0"
version_code = 1
label = "My Super App"
min_sdk = 21
target_sdk = 36

repositories = [
    "https://maven.google.com",
    "https://repo1.maven.org/maven2"
]

# repositories = [
#     "https://maven.aliyun.com/repository/google",
#     "https://maven.aliyun.com/repository/public"
# ]

[dependencies]
"androidx.appcompat:appcompat" = "1.6.1"
"com.google.android.material:material" = "1.9.0"